export { HomePage } from './HomePage'
export { AboutPage } from './AboutPage'
export { SkillsPage } from './SkillsPage'
export { ProjectsPage } from './ProjectsPage'
export { ContactPage } from './ContactPage'
export { MainPage } from './MainPage'